import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/global/Header";
import Footer from "../components/global/Footer";
import NavLoader from "../components/global/NavLoader";
import LinkPrefetcher from "../components/global/LinkPrefetcher";
import { LanguageProvider } from "../components/global/LanguageProvider";

export const metadata: Metadata = {
  title: "Nexa",
  description: "Generated by create next app",

  icons: {
    icon: "/images/logo.svg",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body className="antialiased">
        <LanguageProvider>
          <NavLoader />
          <LinkPrefetcher />
          <Header />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
