import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/global/Header";
import Footer from "../components/global/Footer";
import NavLoader from "../components/global/NavLoader";

export const metadata: Metadata = {
  title: "Nexa",
  description: "Generated by create next app",

  icons: {
    icon: "/images/logo.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="ltr">
      <body className="antialiased">
        <NavLoader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}