import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./globals.css";
import Header from "../components/global/Header";
import Footer from "../components/global/Footer";
import NavLoader from "../components/global/NavLoader";
import LinkPrefetcher from "../components/global/LinkPrefetcher";
import { LanguageProvider, type Lang } from "../components/global/LanguageProvider";

export const metadata: Metadata = {
  title: "Nexa",
  description: "Generated by create next app",

  icons: {
    icon: "/images/logo.svg",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Read the persisted language from the cookie on the server so the very first
  // paint is already correct (RTL for Persian) — independent of client JS/cache.
  const cookieStore = await cookies();
  const lang: Lang = cookieStore.get("nexa-lang")?.value === "fa" ? "fa" : "en";
  const dir = lang === "fa" ? "rtl" : "ltr";

  return (
    <html lang={lang} dir={dir} suppressHydrationWarning>
      <body className="antialiased">
        <LanguageProvider initialLang={lang}>
          <NavLoader />
          <LinkPrefetcher />
          <Header />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
